### ISSUE TITLE
Cast `old_stopwords` to integer

### ISSUE THREAD

**Issue by pypt** [mediacloud/api-client#76]
Hey Dennis,

You might want to cast `old_stopwords` to `int` here:

https://github.com/mediacloud/api-client/blob/e4eb22aa26775a3a5c5e7b65f44564381db2e1d8/mediacloud/api.py#L334-L347

similarly to how it's done with other booleans, e.g.:

```python
'include_stopwords': 1 if include_stopwords is True else 0,
```

the reason being that Perl doesn't really have booleans and so we're expecting integers on the API, so trying to pass booleans to it might lead to various unexpected things.

After doing the change, don't forget to update the link in the blog post as well.

**Comment by dsjen** [comment]
Nice catch. Thank you!
